notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
    - travis@clear-code.com
language: cpp
env:
#  - MYSQL_VERSION=system
  - MYSQL_VERSION=5.5.27
  - MARIADB_VERSION=5.5.25
install:
  - curl https://raw.github.com/groonga/groonga/master/data/travis/setup.sh | sh
  - curl https://raw.github.com/clear-code/cutter/master/data/travis/setup.sh | sh
  - sudo apt-get -y install groonga-tokenizer-mecab
  - tools/travis/install_mysql.sh
before_script:
  - tools/travis/before_script.sh
script:
  - test/run-unit-test.sh
  - test/run-sql-test.sh
