notifications:
  recipients:
    - groonga-mysql-commit@lists.sourceforge.jp
language: cpp
env:
  - MYSQL_VERSION=mysql-system
  - MYSQL_VERSION=mysql-5.5.32
  - MYSQL_VERSION=mysql-5.6.12
  - MYSQL_VERSION=mariadb-5.5.30
  - MYSQL_VERSION=mariadb-10.0.3 MRN_BUNDLED=yes
# matrix:
#   allow_failures:
#     - env: MYSQL_VERSION=mariadb-10.0.3 MRN_BUNDLED=yes
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - tools/travis/script.sh
