notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
    - travis@clear-code.com
language: cpp
env:
  - MYSQL_VERSION=mysql-system
  - MYSQL_VERSION=mysql-5.5.30
  - MYSQL_VERSION=mysql-5.6.10
  - MYSQL_VERSION=mariadb-5.5.30
#matrix:
#  allow_failures:
#    - env: MYSQL_VERSION=mysql-5.6.9-rc
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - tools/travis/script.sh
