notifications:
  email:
    recipients:
      - groonga-mysql-commit@lists.sourceforge.jp
dist: trusty
language: cpp
env:
  - MYSQL_VERSION=mysql-system
  - MYSQL_VERSION=mysql-5.5.48
  - MYSQL_VERSION=mysql-5.6.30
  - MYSQL_VERSION=mariadb-5.5.48
#  - MYSQL_VERSION=mariadb-10.0.23
#  - MYSQL_VERSION=mariadb-10.0.23 CFLAGS=-funsigned-char CXXFLAGS=-funsigned-char
  - MYSQL_VERSION=mariadb-10.0.23 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.0.23 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
#  - MYSQL_VERSION=mariadb-10.1.13
  - MYSQL_VERSION=mariadb-10.1.13 MROONGA_BUNDLED=yes
matrix:
  allow_failures:
#    - env: MYSQL_VERSION=mysql-system
#    - env: MYSQL_VERSION=mariadb-5.5.48
#    - env: MYSQL_VERSION=mariadb-10.0.23
#    - env: MYSQL_VERSION=mariadb-10.0.23 CFLAGS=-funsigned-char CXXFLAGS=-funsigned-char
#    - env: MYSQL_VERSION=mariadb-10.0.23 MROONGA_BUNDLED=yes
    - env: MYSQL_VERSION=mariadb-10.0.23 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
#    - env: MYSQL_VERSION=mariadb-10.1.13
#    - env: MYSQL_VERSION=mariadb-10.1.13 MROONGA_BUNDLED=yes
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - tools/travis/script.sh
