notifications:
  email:
    recipients:
      - groonga-mysql-commit@lists.sourceforge.jp
dist: trusty
language: cpp
env:
  - MYSQL_VERSION=mysql-system
  - MYSQL_VERSION=mysql-5.6
  - MYSQL_VERSION=mysql-5.7
  - MYSQL_VERSION=mariadb-5.5
  - MYSQL_VERSION=mariadb-10.0.34 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.0.34 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
  - MYSQL_VERSION=mariadb-10.1.32 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.2.14 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.2.14 MROONGA_BUNDLED=yes MROONGA_TEST_PS_PROTOCOL=yes
  - MYSQL_VERSION=mariadb-10.3.6 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.3.6 MROONGA_BUNDLED=yes MROONGA_TEST_PS_PROTOCOL=yes
  - MYSQL_VERSION=percona-server-5.6
  - MYSQL_VERSION=percona-server-5.7
matrix:
  allow_failures:
#    - env: MYSQL_VERSION=mysql-system
#    - env: MYSQL_VERSION=mariadb-10.0.34 MROONGA_BUNDLED=yes
#    - env: MYSQL_VERSION=mariadb-10.0.34 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
#    - env: MYSQL_VERSION=mariadb-10.1.32 MROONGA_BUNDLED=yes
   - env: MYSQL_VERSION=mariadb-10.2.14 MROONGA_BUNDLED=yes
   - env: MYSQL_VERSION=mariadb-10.2.14 MROONGA_BUNDLED=yes MROONGA_TEST_PS_PROTOCOL=yes
#    - env: MYSQL_VERSION=mariadb-10.3.6 MROONGA_BUNDLED=yes
#    - env: MYSQL_VERSION=mariadb-10.3.6 MROONGA_BUNDLED=yes MROONGA_TEST_PS_PROTOCOL=yes
#    - env: MYSQL_VERSION=percona-server-5.7
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - travis_wait 30 tools/travis/script.sh
