notifications:
  webhooks:
    - https://webhook.commit-email.info/
dist: trusty
language: cpp
env:
  - MYSQL_VERSION=mysql-system
  - MYSQL_VERSION=mysql-5.6
  - MYSQL_VERSION=mysql-5.7
  - MYSQL_VERSION=mariadb-5.5
  - MYSQL_VERSION=mariadb-10.0.37 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.0.37 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
  - MYSQL_VERSION=mariadb-10.1.37 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.2.19 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.2.19 MROONGA_BUNDLED=yes MROONGA_TEST_PS_PROTOCOL=yes
  - MYSQL_VERSION=mariadb-10.3.11 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.3.11 MROONGA_BUNDLED=yes MROONGA_TEST_PS_PROTOCOL=yes
  - MYSQL_VERSION=percona-server-5.6
  - MYSQL_VERSION=percona-server-5.7
  - MYSQL_VERSION=mysql-8.0.13
# matrix:
#   allow_failures:
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - travis_wait 40 tools/travis/script.sh
