notifications:
  email:
    recipients:
      - groonga-mysql-commit@lists.sourceforge.jp
dist: trusty
language: cpp
env:
  - MYSQL_VERSION=mysql-system
  - MYSQL_VERSION=mysql-5.5.50
  - MYSQL_VERSION=mysql-5.6.31
  - MYSQL_VERSION=mysql-5.7.13
  - MYSQL_VERSION=mariadb-5.5.48
#  - MYSQL_VERSION=mariadb-10.0.26
#  - MYSQL_VERSION=mariadb-10.0.26 CFLAGS=-funsigned-char CXXFLAGS=-funsigned-char
  - MYSQL_VERSION=mariadb-10.0.26 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.0.26 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
#  - MYSQL_VERSION=mariadb-10.1.14
  - MYSQL_VERSION=mariadb-10.1.14 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.2.0 MROONGA_BUNDLED=yes
matrix:
  allow_failures:
#    - env: MYSQL_VERSION=mysql-system
#    - env: MYSQL_VERSION=mariadb-10.0.26
#    - env: MYSQL_VERSION=mariadb-10.0.26 CFLAGS=-funsigned-char CXXFLAGS=-funsigned-char
#    - env: MYSQL_VERSION=mariadb-10.0.26 MROONGA_BUNDLED=yes
    - env: MYSQL_VERSION=mariadb-10.0.26 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
#    - env: MYSQL_VERSION=mariadb-10.1.14
#    - env: MYSQL_VERSION=mariadb-10.1.14 MROONGA_BUNDLED=yes
#    - env: MYSQL_VERSION=mariadb-10.2.0 MROONGA_BUNDLED=yes
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - tools/travis/script.sh
