notifications:
  email:
    recipients:
      - groonga-mysql-commit@lists.sourceforge.jp
language: cpp
env:
  - MYSQL_VERSION=mysql-system
  - MYSQL_VERSION=mysql-5.5.43
  - MYSQL_VERSION=mysql-5.6.24
  - MYSQL_VERSION=mariadb-5.5.43
  - MYSQL_VERSION=mariadb-10.0.18
  - MYSQL_VERSION=mariadb-10.0.18 CFLAGS=-funsigned-char CXXFLAGS=-funsigned-char
  - MYSQL_VERSION=mariadb-10.0.18 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.0.18 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
matrix:
  allow_failures:
#     - env: MYSQL_VERSION=mysql-system
#    - env: MYSQL_VERSION=mariadb-5.5.43
    - env: MYSQL_VERSION=mariadb-10.0.18 MROONGA_BUNDLED=yes
    - env: MYSQL_VERSION=mariadb-10.0.18 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - tools/travis/script.sh
