notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
    - travis@clear-code.com
language: cpp
env:
#  - MYSQL_VERSION=system
  - MYSQL_VERSION=5.5.27
  - MARIADB_VERSION=5.5.25
install:
  - curl https://raw.github.com/groonga/groonga/master/data/travis/setup.sh | sh
  - echo "deb-src http://packages.groonga.org/ubuntu/ $(lsb_release --short --codename) universe" | sudo tee --append /etc/apt/sources.list.d/groonga.list
  - echo "deb http://downloads.sourceforge.net/project/cutter/ubuntu/ $(lsb_release --short --codename) main" | sudo tee /etc/apt/sources.list.d/cutter.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1C837F31
  - sudo apt-get update
  - sudo apt-get -y install cutter-testing-framework
before_script:
  - tools/travis_before_script.sh
script:
  - test/run-unit-test.sh
  - test/run-sql-test.sh
