notifications:
  recipients:
    - kou@clear-code.com
env:
  - MYSQL_VERSION=system
  - MYSQL_VERSION=5.5.25a
install:
  - echo "deb http://packages.groonga.org/ubuntu/ $(lsb_release --short --codename) universe" | sudo tee /etc/apt/sources.list.d/groonga.list
  - sudo apt-get update
  - sudo apt-get -y --allow-unauthenticated install groonga-keyring
  - sudo apt-get -y purge zeromq
  - sudo apt-get update
  - sudo apt-get -y install libgroonga-dev
before_script:
  - tools/travis_before_script.sh
script:
  - test/run-unit-test.sh
  - test/run-sql-test.sh
