notifications:
  recipients:
    - kou@clear-code.com
language: cpp
env:
#  - MYSQL_VERSION=system
  - MYSQL_VERSION=5.5.27
install:
  - echo "deb http://packages.groonga.org/ubuntu/ $(lsb_release --short --codename) universe" | sudo tee /etc/apt/sources.list.d/groonga.list
  - echo "deb-src http://packages.groonga.org/ubuntu/ $(lsb_release --short --codename) universe" | sudo tee --append /etc/apt/sources.list.d/groonga.list
  - echo "deb http://downloads.sourceforge.net/project/cutter/ubuntu/ $(lsb_release --short --codename) main" | sudo tee /etc/apt/sources.list.d/cutter.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1C837F31
  - sudo apt-get update
  - sudo apt-get -y --allow-unauthenticated install groonga-keyring
  - sudo apt-get -y purge zeromq
  - sudo apt-get update
  - sudo apt-get -y install libgroonga-dev cutter-testing-framework
before_script:
  - tools/travis_before_script.sh
script:
  - test/run-unit-test.sh
  - ldd .libs/ha_mroonga.so
  - nm .libs/ha_mroonga.so
  - test/run-sql-test.sh
