notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
    - travis@clear-code.com
language: cpp
env:
#  - MYSQL_VERSION=system
  - MYSQL_VERSION=5.5.27
  - MARIADB_VERSION=5.5.25
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - test/run-unit-test.sh
  - test/run-sql-test.sh
