notifications:
  email:
    recipients:
      - groonga-mysql-commit@lists.sourceforge.jp
language: cpp
env:
  - MYSQL_VERSION=mysql-system
  - MYSQL_VERSION=mysql-5.5.42
  - MYSQL_VERSION=mysql-5.6.23
  - MYSQL_VERSION=mariadb-5.5.42
  - MYSQL_VERSION=mariadb-10.0.17
  - MYSQL_VERSION=mariadb-10.0.17 CFLAGS=-funsigned-char CXXFLAGS=-funsigned-char
  - MYSQL_VERSION=mariadb-10.0.17 MROONGA_BUNDLED=yes
  - MYSQL_VERSION=mariadb-10.0.17 MROONGA_BUNDLED=yes MROONGA_TEST_EMBEDDED=yes
# matrix:
#   allow_failures:
#     - env: MYSQL_VERSION=mysql-system
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - tools/travis/script.sh
