notifications:
  recipients:
    - groonga-mysql-commit@lists.sourceforge.jp
language: cpp
env:
  - MYSQL_VERSION=mysql-system
  - MYSQL_VERSION=mysql-5.5.36
  - MYSQL_VERSION=mysql-5.6.16
  - MYSQL_VERSION=mariadb-5.5.35
  - MYSQL_VERSION=mariadb-10.0.8
  - MYSQL_VERSION=mariadb-10.0.8 MRN_BUNDLED=yes
#  - MYSQL_VERSION=mariadb-10.0.8 MRN_BUNDLED=yes MRN_TEST_EMBEDDED=yes
matrix:
  allow_failures:
#    - env: MYSQL_VERSION=mysql-system
#     - env: MYSQL_VERSION=mariadb-5.5.35
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - tools/travis/script.sh
