version: "{build}"
clone_depth: 1
install:
  - cd ..
  - choco install curl peazip
  - curl -O http://mirror.jmu.edu/pub/mariadb/mariadb-10.0.16/source/mariadb-10.0.16.tar.gz
  - "C:\Program Files\PeaZip\peazip.exe" -ext2here mariadb-10.0.16.tar.gz
  - cd mariadb-10.0.16
  - del storage\mroonga
  - move ..\mroonga storage
  - git clone --depth 1 https://github.com/groonga/groonga.git storage\mroonga\vendor\groonga
  - git clone --depth 1 https://github.com/groonga/groonga-normalizer-mysql.git storage\mroonga\vendor\groonga\vendor\plugins\groonga-normalizer-mysql
build_script:
  - cmake . -G "Visual Studio 12"
  - cmake --build . --config RelWithDebInfo

notifications:
  email:
    - groonga-commit@lists.sourceforge.jp

test: off
