version: "{build}"
clone_depth: 1
install:
  - cd ..
  - choco install curl 7zip.commandline
  - curl -O http://mirror.jmu.edu/pub/mariadb/mariadb-10.0.16/source/mariadb-10.0.16.tar.gz
  - 7z x mariadb-10.0.16.tar.gz
  - 7z x mariadb-10.0.16.tar > nul
  - cd mariadb-10.0.16
  - rmdir /S /Q storage\mroonga\
  - move ..\mroonga storage\mroonga
  - git clone --quiet --depth 1 https://github.com/groonga/groonga.git ..\groonga
  - rmdir /S /Q ..\groonga\test\
  - move ..\groonga storage\mroonga\vendor\groonga
  - git clone --quiet --depth 1 https://github.com/groonga/groonga-normalizer-mysql.git storage\mroonga\vendor\groonga\vendor\plugins\groonga-normalizer-mysql
build_script:
  - cmake . -G "Visual Studio 12"
  - cmake --build . --config RelWithDebInfo

notifications:
  - provider: Email
    to:
      - groonga-mysql-commit@lists.sourceforge.jp
      - kou@clear-code.com
    on_build_status_changed: true

test: off
